import type { NextPage } from "next";
import Head from "next/head";
import { UnorderedList, useMediaQuery } from "@chakra-ui/react";
import useSWR from "swr";
import { PokemonCard } from "components/PokemonCard";
import { request } from "graphql-request";

const fetcher = (query: string) => request("/api/graphql", query);
const QUERY = `
  query Pokemon {
    pokemon {
      count
      next
      results {
        id
        name
        types {
          type {
            name
          }
        }
        sprites {
          other {
            officialArtwork {
              front_default
            }
          }
        }
      }
    }
  }
`;

const Home: NextPage = () => {
  const { data, error } = useSWR<any>(QUERY, fetcher);

  const [isSmallerThan800] = useMediaQuery("(max-width: 800px)");

  return (
    <>
      <Head>
        <title>Pokedex | Main</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <UnorderedList
        as="ul"
        display="flex"
        justifyContent="center"
        width={isSmallerThan800 ? "100%" : "80%"}
        bg="gray.50"
        height="100%"
        flexWrap="wrap"
        gap="10"
        p="10"
        m={0}
        data-testid="pokemon-list"
      >
        {data?.pokemon.results.map((item: any) => (
          <PokemonCard key={item.name} pokemon={item} />
        ))}
      </UnorderedList>
    </>
  );
};

export default Home;
