import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import {
  Box,
  SimpleGrid,
  Grid,
  GridItem,
  Flex,
  Heading,
} from "@chakra-ui/react";
const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Pokedex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SimpleGrid as="ul" data-testid="pokemon-list">
        {Array.from({ length: 1 }, () => undefined).map((item, idx) => (
          <Box as="li" key={idx}>
            Box number {idx}
          </Box>
        ))}
      </SimpleGrid>
    </>
  );
};

export default Home;
